config/routes.rb
Mobadb::Application.routes.draw do
  resources :roles
  resources :role_ratings, except: [:index, :new, :show]
  resources :champ_ratings, except: [:index, :new, :show]
  resources :champions, only: [:show]
  get 'heroes', to: 'champions#heroes'
  get 'champions', to: 'champions#champions'

  resources :memberships, only: [:create, :destroy] do
    post 'accept', on: :member
  end

  resources :teams

  resources :users
  root 'users#index'
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }, length: { maximum: 15 }
  validates :password, presence: true, allow_blank: false, length: { minimum: 3 }

  has_many :memberships, dependent: :destroy
  has_many :teams_invited_to_and_member_of, through: :memberships, source: :teams
  has_many :role_ratings, dependent: :destroy
  has_many :roles, through: :role_ratings
  has_many :champ_ratings, dependent: :destroy

  def is_leader_of_any_team
  	memberships.each do |m|
  		return true if m.team_leader
  	end
  	return false
  end

  def is_leader_of(given_team)
    memberships.each do |m|
      if m.team == given_team and m.team_leader
        return true
      end
    end
    return false
  end

  def is_member_of(given_team)
  	memberships.each do |m|
  		return true if m.team == given_team and m.invitation_status == 1
  	end
  	return false
  end

  def owned_teams
  	teams_array = Array.new

  	memberships.each do |m|
  		teams_array.push m.team if m.team_leader
  	end
  	return teams_array
  end

  def invitations
    invitations_array = Array.new

    memberships.each do |m|
      invitations_array.push m if m.invitation_status == 2
    end
    return invitations_array
  end

  def teams
    teams_array = Array.new

    memberships.each do |m|
      teams_array.push m.team if m.invitation_status == 1
    end
    return teams_array
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @membership = Membership.new
    @games = Game.all
    @character_ratings = @user.champ_ratings
    @role_ratings = @user.role_ratings.order(:score_id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in user_params
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      reset_session
    end
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def sign_in params
      user = User.find_by username: params[:username]
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @user.new_record? %>
        <div class="field">
          <%= f.label :username %><br />
          <%= f.text_field :username %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation  %>
    </div>
    <% if @user.new_record? %>
        <div class="actions">
            <%= f.submit "Sign up" %>
        </div>
    <% else %>
        <div class="actions">
          <%= f.submit "Change password" %>
        </div>
    <% end %>
<% end %>

app/views/users/_game_ratings.html.erb
<div class="row">
  <div class="col-md-6">
    <h3>Your ratings for <%= game.name %></h3>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
   <table class="table table-striped">
     <thead>
       <th><%= game.character_called %></th>
       <th>Skill Level</th>
       <th>Comment</th>
       <th></th>
     </thead>
     <tbody>
      <% if @character_ratings.blank? %>
          <tr><td>No ratings yet!</td></tr>
        <% else %>
          <% @character_ratings.where(game: game).each do |cr| %>
            <tr>
              <td><%= link_to cr.champion.name, cr.champion %></td>
              <td style="background: <%= cr.score.color_hex_code %>"><%= cr.score.description %></td>
              <td><%= cr.comment %></td>
              <% if current_user == @user %>
                <td>
                <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), cr, method: :delete, data: { confirm: 'Are you sure?'} %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
     </tbody>
   </table> 
  </div>


  <div class="col-md-4">
   <table class="table table-striped">
     <thead>
       <th>Role</th>
       <th>Skill Level</th>
       <th>Comment</th>
       <th></th>
     </thead>
     <tbody>
      <% if @role_ratings.blank? %>
          <tr><td>No ratings yet!</td></tr>
        <% else %>
          <% @role_ratings.where(game: game).each do |rr| %>
            <tr>
              <td><%= link_to rr.role.name, rr.role %></td>
              <td style="background: <%= rr.score.color_hex_code %>"><%= rr.score.description %></td>
              <td><%= rr.comment %></td>
              <% if current_user == @user %>
                <td>
                <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), rr, method: :delete, data: { confirm: 'Are you sure?'} %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
     </tbody>
   </table> 
  </div>

  
</div>

app/views/users/_invite_to_team_form.html.erb
<% if current_user and current_user.is_leader_of_any_team and current_user != @user %>
  <div class="row">
    <div class="col-md-4">
      <% # Invite formi, voisi tehda omaksi tiedostokis ja renderata (aattelin 0 = declined(obsolete toistaiseksi), 1 = accepted, eli normal membership ja 2 = pending, invitetty muttei hyvaksytty), tama osa siis nakyy jos kirjautunut kayttaja on jonkun teamin leader %>
      <h3>Invite this player to your team:</h3>
      <%= form_for(@membership) do |f| %>
        <% if @membership.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>
      
            <ul>
            <% @membership.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>

          </div>
        <% end %>
      
        <div class="field">
          <%= f.select :team_id, options_from_collection_for_select(current_user.owned_teams, :id, :name) %>
        </div>
        <div class="field">
          <%= f.hidden_field :user_id, value: @user.id %>
        </div>
        <div class="field">
          <%= f.hidden_field :invitation_status, value: 2 %>
        </div>
        <div class="field">
          <%= f.hidden_field :team_leader, value: false %>
        </div>
        <div class="actions">
          <%= f.submit "Invite" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_teams_and_invitations.html.erb
<div class="row">

  <div class="col-md-4">
   <table class="table table-striped">
     <thead>
       <th><h3>Member of:</h3></th>
     </thead>
     <tbody>
      <% if @user.teams.empty? %>
          <tr><td>Doesn't belong to any teams yet.</td></tr>
        <% else %>
          <% @user.teams.each do |team| %>
            <tr><td><%= link_to team.name, team %></td></tr>
          <% end %>
        <% end %>
     </tbody>
   </table> 
  </div>


  <% if current_user and current_user.id == @user.id %>
    <div class="col-md-4">
     <table class="table table-striped">
       <thead>
         <th><h3>Invitations:</h3></th>
         <th></th>
         <th></th>
       </thead>
       <tbody>

          <% if @user.invitations.blank? %>
            <tr><td>None at the moment!</td></tr>
          <% else %>
            <% @user.invitations.each do |inv| %>
              <tr>
                <td><%= link_to inv.team.name, inv.team %></td>
                <td><%= link_to 'Accept', accept_membership_path(inv), method: :post, class:"btn btn-xs btn-primary" %></td>
                <td><%= link_to 'Decline', inv, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-danger" %></td>
              </tr>
            <% end %>
          <% end %>

       </tbody>
     </table> 
    </div>
  <% end %>
  
</div>

app/views/users/edit.html.erb
<h1>Changing password</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Users</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Username</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.username, user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>
  <%= link_to('New User', new_user_path) unless current_user %>

  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% #Bootstrap hoitaa noticet %>
<h1><%= @user.username %></h1>

<% if current_user and current_user.id == @user.id %>

    <%= link_to('Change password', edit_user_path(@user)) %><br>
    <%= link_to 'Delete your account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

<%= render "teams_and_invitations" %>

<%= render "invite_to_team_form" %>

<% if current_user and current_user.id == @user.id %>
  <%= render partial: "game_ratings", collection: @games, as: :game %>
<% end %>