config/routes.rb
Mobadb::Application.routes.draw do
  resources :roles
  resources :role_ratings, except: [:index, :new, :show]
  resources :champ_ratings, except: [:index, :new, :show]
  resources :champions, only: [:show]
  get 'heroes', to: 'champions#heroes'
  get 'champions', to: 'champions#champions'

  resources :memberships, only: [:create, :destroy] do
    post 'accept', on: :member
  end

  resources :teams

  resources :users
  root 'users#index'
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_ratings, dependent: :destroy
  has_many :users, through: :role_ratings

  validates :name, presence: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  def index
    @roles = Role.all
  end

  def show
    rr = RoleRating.where(role_id: @role.id, user_id: current_user).first
    if rr.nil?
      @rolerating = RoleRating.new
    else
      @rolerating = rr
    end
    @scores = Score.all
    @games = Game.all
  end

  def new
    @role = Role.new
  end

  def edit

  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
    <% if @role.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

          <ul>
            <% @role.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/roles/_role_rating_form.html.erb
<%= form_for(@rolerating) do |f| %>
    <% if @rolerating.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@rolerating.errors.count, "error") %> prohibited this role rating from being saved:</h2>

          <ul>
            <% @rolerating.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      I am <%= f.select :score_id, options_from_collection_for_select(@scores, :id, :description, selected: @rolerating.score_id) %> at this role
    </div>
    <div class="field">
      I play this role in <%= f.select :game_id, options_from_collection_for_select(@games, :id, :name, selected: @rolerating.game_id) %>
    </div>
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_field :comment %>
    </div>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div class="field">
      <%= f.hidden_field :role_id, value: @role.id %>
    </div>
    <div class="actions">
      <%= f.submit "Give rating" %>
    </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

app/views/roles/index.html.erb
<h1>Roles</h1>
<div class="row">
  <div class="col-md-4">
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
      </tr>
      </thead>

      <tbody>
      <% @roles.each do |role| %>
          <tr>
            <td><%= link_to role.name, role %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Role', new_role_path if current_user %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

app/views/roles/show.html.erb
<p>
  <h2><%= @role.name %></h2>
</p>
<p>
  <%= @role.description %>
</p>

<% if current_user %>
    <%= render 'role_rating_form' %>
<% end %>
<%= link_to('Edit role', edit_role_path(@role)) %>
<%= link_to('Destroy role', @role, method: :delete, data: { confirm: 'Are you sure?' }) %>