config/routes.rb
Mobadb::Application.routes.draw do
  resources :roles
  resources :role_ratings, except: [:index, :new, :show]
  resources :champ_ratings, except: [:index, :new, :show]
  resources :champions, only: [:show]
  get 'heroes', to: 'champions#heroes'
  get 'champions', to: 'champions#champions'

  resources :memberships, only: [:create, :destroy] do
    post 'accept', on: :member
  end

  resources :teams

  resources :users
  root 'users#index'
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Teams', teams_path %></li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
  <ul class="dropdown-menu">
	<li><%= link_to 'Roles', roles_url %></li>
	<li><%= link_to 'Heroes (Dota2)', heroes_path %></li>
	<li><%= link_to 'Champions (LoL)', champions_path %></li>
  </ul>
</li>

app/views/layouts/_navigation_links_right.html.erb
<% if current_user.nil? %>
    <li><%= link_to 'Sign in', new_session_path %></li>
    <li><%= link_to 'Sign up', new_user_path %></li>
<% else %>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
	  <ul class="dropdown-menu">
		<li><%= link_to "My Page", current_user %></li>
		<% unless current_user.teams.blank? %>
			<li class="divider"></li>
			<% current_user.teams.each do |team| %>
				<li><%= link_to team.name, team %></li>
			<% end %>
		<% end %>
	  </ul>
	</li>
    <li><%= link_to 'Sign out', signout_path, method: :delete %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MobaDB" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mobadb" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class=".container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>